services:

  api:
    build: ./api
    ports:
      - "8080:8080"

  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb

